version: "3.9"
services:
    database:
        container_name: postgres_prisma
        image: "postgres:15.2-alpine"
        restart: unless-stopped
        ports:
            - 5432:5432
        env_file:
            - .env
        volumes:
            - "./postgresData:/data/postgres"

volumes:
    postgresData:
